project:
  type: book

book:
  title: "Grafos bipartitos en redes de interacción ecológicas"
  author: "Jesús Espinoza & Rosalía Hernández"
  date: "Semestre 2026-1"
  chapters:
    - index.qmd
    # - intro.qmd
    - Sesion1.qmd
    - summary.qmd
    - references.qmd
  page-footer:
    center: "Material desarrollado con [Quarto](https://quarto.org/)"

lang: es

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt




