project:
  type: book

book:
  title: "Grafos bipartitos en redes de interacción ecológicas"
  subtitle: "<span style='color: #696969; font-weight: 400;'>Seminario Bipartita</span> <br> <span style='color: #777777; font-size: 0.85em;'>Semestre 2026-1</span>"  
  author: 
    - "Jesús F. Espinoza"
    - "Rosalía G. Hernández"
  chapters:
    - index.qmd
    #- intro.qmd
    - Sesion1.qmd
    - Sesion2.qmd
    - Sesion3.qmd
    - Sesion4.qmd
    - Sesion5.qmd
    # - summary.qmd
    # - references.qmd
  page-footer:
    center: "Material desarrollado con [Quarto](https://quarto.org/)"

lang: es

language:
  title-block-author-plural: "Autores"

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



